package com.example.SplitApp.Entity;
// Generated 19 Feb, 2018 3:43:10 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * Expences generated by hbm2java
 */
@Entity
@Table(name = "expences", catalog = "splitapp")
public class Expences implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@NotNull
	@Id
	private int expenceId;
	@Temporal(TemporalType.TIMESTAMP)
	private Date date;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "group_id", nullable = false)
	public Groups groupId;
	public int getExpenceId() {
		return expenceId;
	}
	public void setExpenceId(int expenceId) {
		this.expenceId = expenceId;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public Groups getGroupId() {
		return groupId;
	}
	public void setGroupId(Groups groupId) {
		this.groupId = groupId;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
}
